<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/addProduct.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>My ducky world</h1>
        <nav>
            <ul id="nav-barre">
                <li>
                    <?php if (isset($_SESSION['user'])) : ?>
                        Bienvenue <?= $_SESSION['user']['login']; ?>
                        <a href="logout.php" id="logout">Logout</a>
                    <?php else : ?>
                        <a href="login.php">Login</a>
                    <?php endif; ?>
                </li>
                <li><a href="index.php">Accueil</a></li>
                <li><a href="#">Produits</a></li>
                <li><?php if (isset($_SESSION['user'])) : ?>
                        <a href="addProduct.php">Ajouter un produit</a>
                    <?php endif; ?></li>   
                <li><?php if (isset($_SESSION['user'])) : ?>
                        <a href="manageproduct.php">Gérer les produits</a>
                    <?php endif; ?></li>    
            </ul>
        </nav>
    </header>
    <main>
        <h2>Ajouter Produits</h2>
        <section id="form_section">
            <form action="/addProduct.php" method="post" >
                <label for="titre">Titre du produit :</label>
                <input type="text" id="titre" name="titre" class="form-input" required>
                <br>

                <label for="descriptif">Descriptif :</label>
                <textarea id="descriptif" name="descriptif" class="form-input" required></textarea>
                <br>

                <label for="prix">Prix :</label>
                <input type="number" id="prix" name="prix" step="0.01" class="form-input" required>
                <br>

                <label for="image">Image :</label>
                <input type="text" id="image" name="image" class="form-input" required>
                <br>

                <button type="submit" id="add_Btn">Ajouter le produit</button>
            </form>
        </section>
     
    </main>
    <footer>
        <ul>
            <li><a href="#">Contact</a></li>
            <li><a href="#">À propos</a></li>
            <li><a href="#">mentions légales</a></li>
        </ul>
    </footer>   
</body>
</html>