<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/addProduct.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Copse&family=DynaPuff:wght@400..700&family=Gluten:wght@100..900&display=swap" rel="stylesheet">

    <title>Document</title>
</head>
<body>
    <header>
        <h1>My ducky world</h1>
        <nav id="main-nav">
            <ul id="nav-barre">
                <?php if (isset($_SESSION['user'])) : ?>
                    <li class="nav-user">
                        Bonjour <?= htmlspecialchars($_SESSION['user']['login']); ?>
                    </li>
                    <li>
                        <a href="logout.php" id="logout">Logout</a>
                    </li>
                <?php else : ?>
                    <li>
                        <a href="login.php">Login</a>
                    </li>
                <?php endif; ?>
                <li><a href="index.php">Accueil</a></li>
                <li><?php if (isset($_SESSION['user'])) : ?>
                        <a href="addProduct.php">Ajouter un produit</a>
                    <?php endif; ?></li>   
                <li><?php if (isset($_SESSION['user'])) : ?>
                        <a href="manageproduct.php">Gérer les produits</a>
                    <?php endif; ?></li>    
            </ul>
        </nav>
        <div class="header-right">
            <button id="burger-btn">
                <i class="fa-solid fa-bars"></i>
            </button>
        </div>
    </header>
    <main>
        <h2>Ajouter Produits</h2>
        <section id="form_section">
            <form action="/addProduct.php" method="post" >
                <label for="titre">Titre du produit :</label>
                <input type="text" id="titre" name="titre" class="form-input" required>
                <br>

                <label for="descriptif">Descriptif :</label>
                <textarea id="descriptif" name="descriptif" class="form-input" required></textarea>
                <br>

                <label for="prix">Prix :</label>
                <input type="number" id="prix" name="prix" step="0.01" class="form-input" required>
                <br>

                <label for="image">Image :</label>
                <input type="text" id="image" name="image" class="form-input" required>
                <br>

                <button type="submit" id="add_Btn">Ajouter le produit</button>
            </form>
        </section>
     
    </main>
    <footer>
        <ul>
            <li><a href="#">Contact</a></li>
            <li><a href="#">À propos</a></li>
            <li><a href="#">mentions légales</a></li>
        </ul>
    </footer>  
    <script src="./assets/menuBurger.js"></script> 
</body>
</html>