<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>My ducky world</h1>
        <nav>
            <ul id="nav-barre">
                <li><a href="#">Accueil</a></li>
                <li><a href="#">Produits</a></li>
                <li><a href="#">
                    <i id="nav-bar-cart" class="fa-solid fa-cart-arrow-down"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        <form action="/addProduct.php" method="post" >
            <label for="titre">Titre du produit :</label>
            <input type="text" id="titre" name="titre" required>
            <br>

            <label for="descriptif">Descriptif :</label>
            <textarea id="descriptif" name="descriptif" required></textarea>
            <br>

            <label for="prix">Prix :</label>
            <input type="number" id="prix" name="prix" step="0.01" required>
            <br>

            <label for="image">Image :</label>
            <input type="text" id="image" name="image" required>
            <br>

            <button type="submit">Ajouter le produit</button>
        </form>
    </main>
    <footer>
        <ul>
            <li><a href="#">Contact</a></li>
            <li><a href="#">À propos</a></li>
            <li><a href="#">mentions légales</a></li>
        </ul>
    </footer>   
</body>
</html>