<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
    <title>Document</title>
</head>
<body>
    <header>
        <h1>My ducky world</h1>
        <nav>
            <ul id="nav-barre">
                <li>
                    <?php if (isset($_SESSION['user'])) : ?>
                        Bienvenue <?= $_SESSION['user']['login']; ?>
                        <a href="logout.php">Logout</a>
                    <?php else : ?>
                        <a href="login.php">Login</a>
                    <?php endif; ?>
                </li>
                <li><a href="index.php">Accueil</a></li>
                <li><a href="#">Produits</a></li>
                <li><?php if (isset($_SESSION['user'])) : ?>
                        <a href="addProduct.php">Ajouter un produit</a>
                    <?php endif; ?></li>   
                <li><?php if (isset($_SESSION['user'])) : ?>
                        <a href="manageproduct.php">Gérer les produits</a>
                    <?php endif; ?></li>    
                <li><a href="#">
                    <i id="nav-bar-cart" class="fa-solid fa-cart-arrow-down"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        <section id="product-section">
            <h2>Nos produits</h2>
            <div id="product-container">
                <?php foreach($products as $prod): ?>
                <div class="product_card">
                    <div class="img_product">
                        <img src="<?= htmlspecialchars($prod['image']) ?>" 
                            alt="<?= htmlspecialchars($prod['titre']) ?>" 
                        >
                    </div>
                    <h3><?= htmlspecialchars($prod['titre']) ?></h3>
                    <div class="info_product">
                        <p class="product-description"><?= htmlspecialchars($prod['descriptif']) ?></p>
                        <div class="price_and_cart"> 
                            <p class="product_price"><?= htmlspecialchars($prod['prix']) ?>€</p>
                            <a href="#" class="cart-icon">
                                <i class="fa-solid fa-cart-arrow-down"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </section>
    </main>
    <footer>
        <ul>
            <li><a href="#">Contact</a></li>
            <li><a href="#">À propos</a></li>
            <li><a href="#">mentions légales</a></li>
        </ul>
    </footer>   
</body>
</html>